server:
    port: 8084
    session:
      cookie:
        name: UI2SESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#      authorized-grant-types: implicit
      auto-approve-scopes: true
    resource:
#      filter-order: 3
      userInfoUri: http://localhost:8081/auth/rest/hello/principal